#
# Fly.io deployment support with EKG_VARIANT-based configuration.
# Generates fly.toml dynamically based on the EKG_VARIANT environment variable.
#
# Requires:
# - flyctl CLI installed (https://fly.io/docs/hands-on/install-flyctl/)
# - EKG_VARIANT set (oxigraph, graphdb, etc.)
# - FLY_APP_NAME set or derived from EKG_PROJECT_SHORT and EKG_ENV
#
ifndef _MK_FLY_MK_
_MK_FLY_MK_ := 1

#$(info ---> .make/fly.mk)

ifndef GIT_ROOT
GIT_ROOT := $(shell git rev-parse --show-toplevel 2>/dev/null)
endif
ifndef MK_DIR
MK_DIR := $(GIT_ROOT)/.make
endif

include $(MK_DIR)/os.mk

FLYCTL_BIN := $(call where-is-binary,flyctl)

# Fly.io configuration defaults
FLY_REGION ?= iad
FLY_ORG ?= dataroad-232

# Derive app name from project and environment if not set
# Format: <prefix>-<variant>-<env> (e.g., business-composer-oxigraph-production)
# FLY_APP_PREFIX can be set in .env files, defaults to EKG_PROJECT_SHORT
FLY_APP_PREFIX ?= $(EKG_PROJECT_SHORT)
ifdef FLY_APP_PREFIX
ifdef EKG_VARIANT
ifdef EKG_ENV
FLY_APP_NAME ?= $(FLY_APP_PREFIX)-$(EKG_VARIANT)-$(EKG_ENV)
endif
endif
endif

# Environment-specific resource defaults (preview is smaller)
ifeq ($(EKG_ENV),preview)
_FLY_DEFAULT_MEMORY := 512mb
_FLY_DEFAULT_CPUS := 1
_FLY_DEFAULT_VOLUME_SIZE := 1
else
_FLY_DEFAULT_MEMORY := 1gb
_FLY_DEFAULT_CPUS := 2
_FLY_DEFAULT_VOLUME_SIZE := 10
endif

# Variant-specific settings
ifeq ($(EKG_VARIANT),oxigraph)
FLY_DOCKERFILE ?= Dockerfile.oxigraph
FLY_INTERNAL_PORT ?= 7878
FLY_MEMORY ?= $(_FLY_DEFAULT_MEMORY)
FLY_CPUS ?= $(_FLY_DEFAULT_CPUS)
FLY_VOLUME_NAME ?= oxigraph_data
FLY_VOLUME_SIZE ?= $(_FLY_DEFAULT_VOLUME_SIZE)
FLY_MOUNT_DEST ?= /data
FLY_PROCESS_CMD ?= serve --location /data --bind 0.0.0.0:7878
FLY_ENV_VARS ?= RUST_LOG = "info"
FLY_BUILD_ARGS ?=
endif

ifeq ($(EKG_VARIANT),graphdb)
FLY_DOCKERFILE ?= Dockerfile.graphdb
FLY_INTERNAL_PORT ?= 7200
FLY_MEMORY ?= 2gb
FLY_CPUS ?= $(_FLY_DEFAULT_CPUS)
FLY_VOLUME_NAME ?= graphdb_data
FLY_VOLUME_SIZE ?= $(_FLY_DEFAULT_VOLUME_SIZE)
FLY_MOUNT_DEST ?= /opt/graphdb/data
FLY_PROCESS_CMD ?=
FLY_ENV_VARS ?= GDB_HEAP_SIZE = "1g"
FLY_BUILD_ARGS ?= EKG_ENV=$(EKG_ENV)
endif

# fly.toml output path
FLY_TOML ?= $(GIT_ROOT)/fly.toml

.PHONY: fly-check
ifdef FLYCTL_BIN
fly-check:
	@echo "Using flyctl at $(FLYCTL_BIN)"
else
fly-check:
	@echo "flyctl not found. Install it with: curl -L https://fly.io/install.sh | sh"
	@exit 1
endif

#
# Generate fly.toml based on EKG_VARIANT
#
.PHONY: fly-generate-toml
fly-generate-toml:
ifndef EKG_VARIANT
	$(error EKG_VARIANT is not set. Set it in .env or environment)
endif
ifndef FLY_APP_NAME
	$(error FLY_APP_NAME is not set. Set FLY_APP_PREFIX, EKG_VARIANT, and EKG_ENV)
endif
	@echo "Generating $(FLY_TOML) for $(EKG_VARIANT) ($(FLY_APP_NAME))..."
	@printf '%s\n' \
		'# Fly.io configuration for $(EKG_VARIANT) triplestore' \
		'# Generated by: gmake fly-generate-toml' \
		'# EKG_VARIANT=$(EKG_VARIANT), EKG_ENV=$(EKG_ENV)' \
		'# See: https://fly.io/docs/reference/configuration/' \
		'' \
		'app = "$(FLY_APP_NAME)"' \
		'primary_region = "$(FLY_REGION)"' \
		'' \
		'[build]' \
		'dockerfile = "$(FLY_DOCKERFILE)"' \
		'' > $(FLY_TOML)
	@if [ -n "$(FLY_BUILD_ARGS)" ]; then \
		printf '%s\n' \
			'' \
			'[build.args]' \
			'$(FLY_BUILD_ARGS)' \
			'' >> $(FLY_TOML); \
	fi
	@printf '%s\n' \
		'[env]' \
		'$(FLY_ENV_VARS)' \
		'' >> $(FLY_TOML)
	@if [ -n "$(FLY_PROCESS_CMD)" ]; then \
		printf '%s\n' \
			'[processes]' \
			'app = "$(FLY_PROCESS_CMD)"' \
			'' >> $(FLY_TOML); \
	fi
	@printf '%s\n' \
		'[mounts]' \
		'source = "$(FLY_VOLUME_NAME)"' \
		'destination = "$(FLY_MOUNT_DEST)"' \
		'' \
		'[http_service]' \
		'internal_port = $(FLY_INTERNAL_PORT)' \
		'force_https = true' \
		'auto_stop_machines = "off"' \
		'auto_start_machines = true' \
		'min_machines_running = 1' >> $(FLY_TOML)
	@if [ -n "$(FLY_PROCESS_CMD)" ]; then \
		printf '%s\n' 'processes = ["app"]' >> $(FLY_TOML); \
	fi
	@printf '%s\n' \
		'' \
		'[http_service.concurrency]' \
		'type = "connections"' \
		'hard_limit = 100' \
		'soft_limit = 50' \
		'' \
		'[[http_service.checks]]' \
		'interval = "15s"' \
		'timeout = "5s"' \
		'grace_period = "10s"' \
		'method = "GET"' \
		'path = "/"' \
		'' \
		'[[vm]]' \
		'memory = "$(FLY_MEMORY)"' \
		'cpu_kind = "shared"' \
		'cpus = $(FLY_CPUS)' >> $(FLY_TOML)
	@echo "Generated $(FLY_TOML)"

#
# Deploy to Fly.io (generates fly.toml first)
#
.PHONY: fly-deploy
fly-deploy: fly-check fly-generate-toml
ifndef FLY_API_TOKEN
	$(error FLY_API_TOKEN is not set)
endif
	@echo "Deploying $(FLY_APP_NAME) to Fly.io..."
	# Create app (no-op if already exists)
	$(FLYCTL_BIN) apps create $(FLY_APP_NAME) --org $(FLY_ORG) || true
	# Create volume if none exists
	@EXISTING_VOLUMES=$$($(FLYCTL_BIN) volumes list -a $(FLY_APP_NAME) --json 2>/dev/null | jq length); \
	if [ "$$EXISTING_VOLUMES" = "0" ] || [ -z "$$EXISTING_VOLUMES" ]; then \
		echo "Creating volume $(FLY_VOLUME_NAME)..."; \
		$(FLYCTL_BIN) volumes create $(FLY_VOLUME_NAME) --size $(FLY_VOLUME_SIZE) --region $(FLY_REGION) -a $(FLY_APP_NAME) --yes; \
	else \
		echo "Volume already exists ($$EXISTING_VOLUMES volumes)"; \
	fi
	# Set EKG_AGE_KEY secret if provided (needed for GraphDB license decryption)
	@if [ -n "$(EKG_AGE_KEY)" ]; then \
		echo "Setting EKG_AGE_KEY secret..."; \
		echo "$(EKG_AGE_KEY)" | $(FLYCTL_BIN) secrets set EKG_AGE_KEY=- -a $(FLY_APP_NAME); \
	fi
	# Deploy with build args if specified
	@if [ -n "$(FLY_BUILD_ARGS)" ]; then \
		$(FLYCTL_BIN) deploy --remote-only --app $(FLY_APP_NAME) --build-arg $(FLY_BUILD_ARGS); \
	else \
		$(FLYCTL_BIN) deploy --remote-only --app $(FLY_APP_NAME); \
	fi

#
# Show current fly.toml configuration
#
.PHONY: fly-show-config
fly-show-config:
	@echo "EKG_VARIANT: $(EKG_VARIANT)"
	@echo "EKG_ENV: $(EKG_ENV)"
	@echo "FLY_APP_NAME: $(FLY_APP_NAME)"
	@echo "FLY_DOCKERFILE: $(FLY_DOCKERFILE)"
	@echo "FLY_INTERNAL_PORT: $(FLY_INTERNAL_PORT)"
	@echo "FLY_MEMORY: $(FLY_MEMORY)"
	@echo "FLY_CPUS: $(FLY_CPUS)"
	@echo "FLY_VOLUME_NAME: $(FLY_VOLUME_NAME)"
	@echo "FLY_VOLUME_SIZE: $(FLY_VOLUME_SIZE)"

#$(info <--- .make/fly.mk)

endif # _MK_FLY_MK_
